"""Added course_code index

Revision ID: 7118d1472439
Revises: d35e72bb5138
Create Date: 2026-08-06 22:47:42.025539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7118d1472439'
down_revision: Union[str, Sequence[str], None] = 'd35e72bb5138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_course_code', 'courses', ['course_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_course_code', table_name='courses')
    # ### end Alembic commands ###
